[package]
name = "tank"
version = "0.1.0"
authors = ["securityinnovation <satish28888@gmail.com>"]
edition = "2018"


[dependencies]
piston = "0.46.0"
piston2d-graphics = "0.32.0"
pistoncore-glutin_window = "0.59.0"
piston2d-opengl_graphics = "0.65.0"
